version: '3.8'
services:
  workout-tracker:
    image: ennoluto/workout-tracker:latest
    container_name: workout-tracker
    ports:
      - "5000:5000"  # host:container (change host port if you want, e.g. "272:5000")
    environment:
      - PORT=5000
      - SQLITE_DB_PATH=sqlite:////app/data/app.db
    volumes:
      - ./data:/app/data