"""Add notes field to TemplateExercise

Revision ID: 8888f02a39bb
Revises: 
Create Date: 2025-06-15 15:43:42.191187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8888f02a39bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_exercise', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
